AnalyticsDashboard3/Models/Advertising.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsDashboard3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertising
    {
        public short ID { get; set; }
        public Nullable<int> NumberOfClicks { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public double Price { get; set; }
        public string Category { get; set; }
    }
}

AnalyticsDashboard3/Controllers/AdvertisingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using AnalyticsDashboard3.Models;
using Highsoft.Web.Mvc.Charts;

namespace AnalyticsDashboard3.Controllers
{
    public class AdvertisingsController : Controller
    {
        private AnalyticsDashboardDB db = new AnalyticsDashboardDB();

        // GET: Advertisings
        public ActionResult Index()
        {
            List<Series> listSeries = new List<Series>();
            int currentYear = DateTime.Today.Year;

            listSeries = GetDataNumberOfClicks(currentYear, "");

            ViewData["ListSeriesPrice"] = listSeries;
            GetDataList();
            FilterAdvertising filterAdvertising = new FilterAdvertising(currentYear, "");

            return View(filterAdvertising);
        }

        // POST: Expenses
        [HttpPost]
        public ActionResult Index(int? SelectedYear, string SelectedCategory)
        {
            int getYear;

            getYear = SelectedYear.GetValueOrDefault();
            

            var listOfDate = db.Advertisings
                                    .Where(p => p.Category == SelectedCategory
                                            && p.Date.Value.Year == getYear)
                                    .GroupBy(p => p.Date)
                                    .Select(g => g.FirstOrDefault().Date.ToString()).ToList();

            ViewData["XMonths"] = listOfDate;
            
            List<Series> listSeries = new List<Series>();
            listSeries = GetDataNumberOfClicks(getYear, SelectedCategory);
            ViewData["ListSeriesPrice"] = listSeries;

            GetDataList();
            FilterAdvertising filterExpense = new FilterAdvertising(getYear, SelectedCategory);
            return View(filterExpense);
        }

        private List<Series> GetDataNumberOfClicks(int selectedYear, string selectedCategory)
        {
            List<Series> listSeries = new List<Series>();

            var listCategory = db.Advertisings
                                .GroupBy(p => p.Category)
                                .Select(group => group.FirstOrDefault().Category)
                                .ToList();

            var listMonths = db.Advertisings
                                .Where(p => p.Date.Value.Year == selectedYear)
                                .GroupBy(p => p.Date.Value.Month)
                                .Select(group => group.FirstOrDefault().Date.Value.Month)
                                .ToList();

            if (string.IsNullOrEmpty(selectedCategory))
            {
                foreach (string eachCategory in listCategory)
                {
                    List<LineSeriesData> amountData = new List<LineSeriesData>();

                    foreach (int eachMonth in listMonths)
                    {
                        var priceValues = db.Advertisings
                                        .Where(p => p.Category == eachCategory
                                                && p.Date.Value.Year == selectedYear
                                                && p.Date.Value.Month == eachMonth)
                                        .GroupBy(p => new { p.Date })
                                        .Select(g => g.Sum(item => item.NumberOfClicks)).ToList();


                        priceValues.ForEach(p => amountData.Add(new LineSeriesData { Y = p }));
                    }

                    listSeries.Add(new LineSeries
                    {
                        Name = eachCategory,
                        Data = amountData
                    });
                }
            }
            else
            {
                List<LineSeriesData> amountData = new List<LineSeriesData>();

                foreach (int eachMonth in listMonths)
                {
                    var priceValues = db.Advertisings
                                    .Where(p => p.Category == selectedCategory
                                            && p.Date.Value.Year == selectedYear
                                            && p.Date.Value.Month == eachMonth)
                                    .GroupBy(p => new { p.Date })
                                    .Select(g => g.Sum(item => item.NumberOfClicks)).ToList();


                    priceValues.ForEach(p => amountData.Add(new LineSeriesData { Y = p }));
                }

                listSeries.Add(new LineSeries
                {
                    Name = selectedCategory,
                    Data = amountData
                });
            }

            return listSeries;
        }


        private void GetDataList()
        {
            int startYear = DateTime.Today.Year - 3;
            ViewBag.Years = new SelectList(Enumerable.Range(startYear, 4)
                .Select(x =>
                   new SelectListItem()
                   {
                       Text = x.ToString(),
                       Value = x.ToString()
                   }), "Value", "Text");


            var lstCategory = db.Advertisings.GroupBy(x => x.Category).ToList();
            ViewBag.Categories = new SelectList(lstCategory.AsEnumerable()
                                .Select(row => new SelectListItem()
                                {
                                    Text = row.Key,
                                    Value = row.Key
                                })
                                , "Value", "Text");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnalyticsDashboard3/Views/Advertisings/Index.cshtml
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
@using Highsoft.Web.Mvc.Charts
@model AnalyticsDashboard3.Models.FilterAdvertising

@{
    ViewBag.Title = "Advertising Chart";
}

<h2>Advertising Chart</h2>

@using (Html.BeginForm("Index", "Advertisings", FormMethod.Post, new { @class = "form-inline" }))
{
    @*@Html.ValidationSummary(true)*@

    @Html.DropDownListFor(model => model.SelectedYear, (IEnumerable<SelectListItem>)ViewBag.Years, "Year", new { @class = "form-control" })
    @Html.DropDownListFor(model => model.SelectedCategory, (IEnumerable<SelectListItem>)ViewBag.Categories, "Category", new { @class = "form-control" })

    <input type="submit" value="Filter" class="btn btn-primary" />
}

@(Html.Highsoft().GetHighcharts(
    new Highcharts
    {
        Title = new Title
        {
            Text = "Monthly Average Number Of Clicks",
            X = -20
        },
        Subtitle = new Subtitle
        {
            Text = "Source: Team Awesome",
            X = -20
        },
        XAxis = new List<XAxis>
        {
            new XAxis
            {
                Categories = new List<string> { "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                            "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" },
            }
        },
        YAxis = new List<YAxis>
        {
            new YAxis
            {
                Title = new YAxisTitle
                {
                    Text = "Number of clicks"
                },
                PlotLines = new List<YAxisPlotLines>
                {
                        new YAxisPlotLines
                    {
                        Value = 0,
                        Width = 1,
                        Color = "#808080"
                    }
                }
            }
        },
        Tooltip = new Tooltip
        {
            PointFormat = "{point.y} - {point.custom1} - {point.custom2}"
            //ValueSuffix = "°C"
        },
        Legend = new Legend
        {
            Layout = LegendLayout.Vertical,
            Align = LegendAlign.Right,
            VerticalAlign = LegendVerticalAlign.Middle,
            BorderWidth = 0
        },
        Series = @ViewData["ListSeriesPrice"] as List<Series>
    }
, "chart")
)